site_name: "picpay-docs-digital-payments"
nav:
  - 'Visão Geral': index.md
  - 'Recursos': pages/recursos.md
  - 'Dependências': pages/dependencias.md
  - 'Começar': pages/comecar.md
  - 'Conteúdo Relacionado': pages/relacionado.md
  - 'Contato': pages/contato.md
plugins:
  - picpay-docs-digital-payments
